services:
  plex: # <IP-ADDR>:32400/web/
    image: plexinc/pms-docker
    container_name: plex_container
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${MEDIA_DIR}/appdata/PlexMediaServer:/config
      - ${MEDIA_DIR}/media:/data/
      - /dev/shm/:/transcode
    environment:
      - TZ=America/Winnipeg
      - VERSION=latest
      # - PLEX_CLAIM=
      # - PLEX_UID=99
      # - PLEX_GID=100

  jellyfin: # <IP-ADDR>:5055/
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    user: 1000:1000
    network_mode: "host"
    volumes:
      - ${MEDIA_DIR}/appdata/jellyfin:/config

  sonarr: # <IP-ADDR>:8989/
    image: linuxserver/sonarr
    container_name: sonarr_container
    restart: unless-stopped
    volumes:
      - /dev/rtc:/dev/rtc
      - ${MEDIA_DIR}/appdata/sonarr:/config
      - ${MEDIA_DIR}/media:/media/
    environment:
      - TZ=America/Winnipeg
      - PUID=1000
      - PGID=1000
    ports:
      - 8989:8989

  radarr: # <IP-ADDR>:7878/
    image: linuxserver/radarr
    container_name: radarr_container
    restart: unless-stopped
    volumes:
      - ${MEDIA_DIR}/appdata/radarr:/config
      - ${MEDIA_DIR}/media:/media
    environment:
      - TZ=America/Winnipeg
      - PUID=1000
      - PGID=1000
    ports:
      - 7878:7878

  prowlarr: # <IP-ADDR>:9696/
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr_container
    restart: unless-stopped
    volumes:
      - ${MEDIA_DIR}/appdata/prowlarr:/config
    environment:
      - TZ=America/Winnipeg
      - UMASK=022
      - PUID=1000
      - PGID=1000
    ports:
      - 9696:9696

  binhex-qbittorrentvpn: # <IP-ADDR>:8080/
    # On first run, credentials are "admin":"adminadmin"
    image: binhex/arch-qbittorrentvpn
    container_name: binhex_qbittorrentvpn_container
    restart: unless-stopped
    volumes:
      - ${MEDIA_DIR}/appdata/binhex-qbittorrentvpn:/config
      - ${MEDIA_DIR}/media:/media/
    environment:
      - TZ=America/Winnipeg
      - WEBUI_PORT=8080
      - STRICT_PORT_FORWARD=yes
      - LAN_NETWORK="192.168.1.0/24"
      - ENABLE_PRIVOXY=no
      - DEBUG=false
      - UMASK=000
      - PUID=1000
      - PGID=1000
      - VPN_ENABLED=no
      # - VPN_USER=
      # - VPN_PASS=
      # - VPN_PROV= # pia, airvpn, custom
      # - VPN_OPTIONS=
    ports:
      - 8080:8080
      - 6881:6881
      - 8118:8118
      - 6889:6889
      - 16889:16889

  seerr: # <IP-ADDR>:5055/
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    restart: unless-stopped
    init: true
    volumes:
      - ${MEDIA_DIR}/appdata/seerr:/app/config
    environment:
      - TZ=America/Winnipeg
      - LOG_LEVEL=info
      - UMASK=022
      - PUID=1000
      - PGID=1000
    ports:
      - 5055:5055
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

  portainer: # <IP-ADDR>:9000/
    image: portainer/portainer
    container_name: portainer_container
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MEDIA_DIR}/appdata/portainer:/data
    environment:
      - TZ=America/Winnipeg
    ports:
      - 9000:9000
